# Generated by Django 5.2 on 2025-05-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='constraseña',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
