# Generated by Django 5.2 on 2025-05-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animaapp', '0002_usuario_constraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='constraseña',
        ),
    ]
